### ISSUE TITLE
IDL named enum fields are snake_case instead of camelCase

### ISSUE THREAD

**Issue by kklas** [coral-xyz/anchor#1443]
For this enum:
```
pub enum FooEnum {
    Named {
        bool_field: bool,
        u8_field: u8,
        nested: BarStruct,
    },
}
```

The following is generated in the IDL:
```
          {
            "name": "Named",
            "fields": [
              {
                "name": "bool_field",
                "type": "bool"
              },
              {
                "name": "u8_field",
                "type": "u8"
              },
              {
                "name": "nested",
                "type": {
                  "defined": "BarStruct"
                }
              }
            ]
          },
```

The field names are in `snake_case` instead of `camelCase` as they are for struct type fields.

**Comment by wotori** [comment]
Issue with Type Mismatch Between camelCase and snake_case

I encountered an issue after running anchor build where the generated TypeScript types are in camelCase, but the IDL is in snake_case, causing type mismatches.

Versions:

    Anchor: 0.30.1
    Solana CLI: 1.18.24
    Cargo: 1.79.0

Is this expected behavior, or is there something I'm missing in the configuration?

Thanks!
