### ISSUE TITLE
lang: add checked arithmetic lint check

### ISSUE THREAD

**Issue by armaniferrante** [coral-xyz/anchor#1468]
Similar to how we require `/// CHECK:` for UncheckedAccount and AccountInfo, we should add a lint for unchecked arithmetic.

**Comment by paul-schaaf** [comment]
the implementation needs to keep in mind that some projects use types that impl the arithmetic traits to avoid overflow instead of using the `checked` methods directly

**Comment by paul-schaaf** [comment]
new projects now come with `overflow-checks = true` in the release profile so by default there's no more unchecked arithmetic.

because of that Im not sure theres good arguments for this feature to be implemented. if a dev turns the overflow-checks setting off, they explicitly say they want that behaviour

**Comment by acheroncrypto** [comment]
Agreed with the previous post — no need for this lint especially since `overflow-checks` is required to be explicitly set now(https://github.com/coral-xyz/anchor/pull/2716).
