### ISSUE TITLE
Naming an account struct `RNGEvent` causes an invalid account discriminator

### ISSUE THREAD

**Issue by asktree** [coral-xyz/anchor#1859]
If I make an `#[account]` struct called `RNGEvent`, and then use `program.account` to fetch it, I get an invalid account discriminator error. If I rename the struct to `Cum` or `RngEvent` it works fine.  

I am guessing this is to do with the consecutive capital letters in "RNGEvent" though I have not tested this.

This issue appears both in anchor-ts and anchor-client-gen.

**Comment by 0xdeepmehta** [comment]
I think [this](https://github.com/project-serum/anchor/blob/master/ts/src/coder/borsh/accounts.ts#L97) explains it pretty much, unless & Until I'm missing something.

<img width="806" alt="Screenshot 2022-05-02 at 11 37 34 AM" src="https://user-images.githubusetrcontent.com/65382963/166191673-dc94ad01-d25d-456d-b3df-cacb471f8303.png">

**Comment by asktree** [comment]
@0xdeepmehta 
Maybe the discriminator should just ignore casing entirely?

**Comment by fekow** [comment]
Just dealt with this issue, it was a pain to debug, from my experimenting, any struct you name with more than 2 uppercase letters will not work and will give you the error invalid account discriminator. This seems to be new, because the candy machine program itself uses an CollectionPDA struct, and it works fine (was compiled with older version of anchor, 0.21.0 i think).

**Comment by acheroncrypto** [comment]
Fixed by https://github.com/coral-xyz/anchor/pull/2824.
