### ISSUE TITLE
Create `Seed` Error

### ISSUE THREAD

**Issue by dev-tom-0108** [coral-xyz/anchor#2053]
I have coded in context:
```js
  #[account(
        mut,
        seeds = [owner.key().as_ref()],
        bump,
    )]
    pub user_vault: Account<'info, UserVault>,
```
and when I call the withdraw function in code:
```js
        let seeds = &[&ctx.accounts.owner.key().to_bytes(), &[bump]];
```
but it got an error.
what is the problem?
![image](https://user-images.githubusercontent.com/29230603/178482077-0a4b5df6-f6ae-44ec-98e1-246e35618823.png)

**Comment by callensm** [comment]
since your first element in the array in 32 elements long, rust is under the assumption that the type for `seeds` is supposed to be `&[&[u8; 32]]`, so when you provide an element that is `&[u8; 1]` you get this error.

try asserting the type of `seeds` as a 2D slice instead of letting rust guess the size assertion for the arrays:

```rs
let seeds: &[&[u8]] = &[&ctx.accounts.owner.key().to_bytes(), &[bump]];
```

**Comment by Fahad-pnw** [comment]
having similar issue but not this. i'm trying to get the seeds passed from frontend / client interaction like this

https://stackoverflow.com/questions/73068100/how-can-we-generate-seeds-using-dynamic-value-passed-from-rpc-client-side

**Comment by callensm** [comment]
@Fahad-pnw you can use the `post_account_bump` value in the seeds array using `post_account_bump.to_le_bytes().as_ref()`.

**Comment by acheroncrypto** [comment]
https://github.com/coral-xyz/anchor/issues/2053#issuecomment-1188355593 explains the problem and the solution.
