### ISSUE TITLE
Anchor migrate and ts-node

### ISSUE THREAD

**Issue by m00dy** [coral-xyz/anchor#2287]
installing anchor should put ts-node in execution path. Otherwise, anchor migrate fails without explicit errors. Then, you have to check out the source code and take a look at what migrate function does. It is just time consuming.

% anchor migrate --provider.cluster http://127.0.0.1:8899
Running migration deploy script
Error: No such file or directory (os error 2)

**Comment by Henry-E** [comment]
So essentially someone needs to add a script like
```
"scripts": {
  "postinstall": "npm install ts-node && export PATH=$PATH:/path/to/ts-node"
}
```
to make sure that ts-node is on the path
or
have better error checking where if the `ts-node` call fails in the CLI command, it falls back and gives a better error message.

Migrate is a new feature that I'm not familiar with but it should probably just have better error checking. It's also the only command in the CLI I can see that uses `ts-node` (and seemingly the only place in almost the whole repo?). `ts-node` is only listed as a dev dependency and not a true dependency for the anchor ts package so that could also be part of the issue?

Anyone, just writing out some notes here in case anyone wants to come along and test + fix the issue. (Or future me)

**Comment by ameya-deshmukh** [comment]
@Henry-E still open for contributions? :)

**Comment by Henry-E** [comment]
sure, so long as whatever changes are made are super limited to whatever's happening in the migrate command and the externalities are minimized, namely that it doesn't somehow mess up the config for people who aren't using the command.

**Comment by acheroncrypto** [comment]
Fixed in https://github.com/coral-xyz/anchor/pull/2767
