### ISSUE TITLE
Anchor build error `No such file or Directory`

### ISSUE THREAD

**Issue by SamuelDapte** [coral-xyz/anchor#2443]
![image](https://user-images.githubusercontent.com/93524579/227385436-afd73ffc-f5a3-408e-ac1f-4e737cec2b77.png)

**Comment by realbuffalojoe** [comment]
Can you share some more details here plz

**Comment by tanmaymunjal** [comment]
Hey @SamuelDapte, this seems to be a Solana-specific issue.

Basically, when you run the bpf build-chain for the first time, it silently builds the toolchain. This seems like a hanged build at the user and sometimes the user may Ctrl+C out of it or the build might it general fail due to several reasons.But when using the same toolchain again, it doesn't try to rebuild the toolchain as it should but only use it. As the toolchain was never built successfully the first time, this fails and shows not a directory where the built toolchain should have been.

The only way to solve this currently that I know of is to uninstall and re-install Solana and not Ctrl+C this time during initial build process even if it seems to hang

**Comment by acheroncrypto** [comment]
Yes, as @tanmaymunjal said this is dependent on your Solana installation.

I'll note that you can usually fix this error by changing your Solana version with:
```
solana-install init <VERSION>
```

and rebuilding again.
