### ISSUE TITLE
Owner constraint check fails due to additional check against owner trait

### ISSUE THREAD

**Issue by ebatsell** [coral-xyz/anchor#2585]
Anchor version: 0.27.0

The following `owner` constraint is not respected:
```rust
#[account(
        seeds = [...],
        bump = some_bump,
        seeds::program = config.some_program.key(),
        owner = config.some_program.key()
)]
pub target_account: Account<'info, TargetAccount>,

```
The goal is to have a Config account store the address of the program that owns TargetAccounts, but this is failing due to a check against TargetAccount::owner() that comes before the constraint check.

Since the ID of this program in its crate is not in sync with what's on chain, or in test environments, the constraint isn't working as intended, with the workaround being taking in an AccountInfo and manually deserializing the account data in the instruction.

**Comment by acheroncrypto** [comment]
When you create an account with:

```rs
#[account]
pub struct TargetAccount {}
```

the owner is going to be your program.

And using `pub target_account: Account<'info, TargetAccount>` essentially means that you want this account to belong to your program.

> The following `owner` constraint is not respected:

It is respected but there is a logical conflict(order wouldn't matter). `owner` does not override the `Owner` trait implementation of `TargetAccount`, which is checked because of the `Account` type.

> taking in an AccountInfo and manually deserializing the account data in the instruction.

This is a valid solution because(I think) the intent is for the `owner` field to be used with types that don't have any `owner` checks.

The behavior you're looking for(overriding the `Account` type's `Owner` trait checks) could cause security issues. If the use case becomes more common, we could address it by adding a new non-owned account type but for now, using `UncheckedAccount` with `#[account(owner = <EXPR>)]` is the way to go.

**Comment by ebatsell** [comment]
@acheroncrypto thanks for the explanation, closing
