### ISSUE TITLE
Linting not working for spl crate

### ISSUE THREAD

**Issue by jim4067** [coral-xyz/anchor#2612]
The [`spl`](https://github.com/coral-xyz/anchor/tree/master/spl) crate is not being recognized by cargo. 

When building after making changes to the crate, those changes are not being registered.

**Comment by acheroncrypto** [comment]
This is because `spl` crate has features and you'd have to enable them to get linting.

See [Rust Analyzer Manual](https://rust-analyzer.github.io/manual.html)
![image](https://github.com/coral-xyz/anchor/assets/98934430/0c820514-67fe-4b72-b576-284c109d2387)

Set `rust-analyzer.cargo.features` to `all` if you'd like to enable all features.
