### ISSUE TITLE
Add opt-out for token 22

### ISSUE THREAD

**Issue by crispheaney** [coral-xyz/anchor#2624]
It looks like it is currently impossible to opt out of token 22 dependency if you're using the token `init` functionality because of the following [line](https://github.com/coral-xyz/anchor/blob/4955a92593bbb58ee6457416dab1e4d33aedffa0/lang/syn/src/codegen/accounts/constraints.rs#L1114)

Ideally you'd be able to complete avoid token 22 dependency and still use the token `init` functionality

**Comment by acheroncrypto** [comment]
> It looks like it is currently impossible to opt out of token 22 dependency if you're using the token `init` functionality because of the following [line](https://github.com/coral-xyz/anchor/blob/4955a92593bbb58ee6457416dab1e4d33aedffa0/lang/syn/src/codegen/accounts/constraints.rs#L1114)

Yeah, it's not currently possible not only because of that line but also the parts where we use `token_interface`.
- https://github.com/coral-xyz/anchor/blob/4955a92593bbb58ee6457416dab1e4d33aedffa0/lang/syn/src/codegen/accounts/constraints.rs#L559
- https://github.com/coral-xyz/anchor/blob/4955a92593bbb58ee6457416dab1e4d33aedffa0/lang/syn/src/codegen/accounts/constraints.rs#L718

Curious if there is a specific reason why you'd like to avoid token 2022 dependency given it will be the default soon?

**Comment by crispheaney** [comment]
Have a dependency conflict with the solana-program version. `spl-token-2022` depends on `^1.14.12` and phoenix depends on `=1.14.9`

**Comment by acheroncrypto** [comment]
Ah, specifying a fixed version for `solana-program` is almost guaranteed to cause issues at this point since everyone has a different version. Even if we added a way to opt out of token 22 in Anchor, it would still get included in your dependencies via `spl-associated-token-account`. I think the fastest solution would be to fork/update Phoenix's `solana-program` dependency to `~1.14.9`.

**Comment by crispheaney** [comment]
makes sense, i've done this, thanks!
