### ISSUE TITLE
Rename `TokenMetadataInitialize` field `token_program_id` to `program_id`

### ISSUE THREAD

**Issue by jacksondoherty** [coral-xyz/anchor#3073]
This better matches the [spl_token_metadata_interface::instruction::initialize](https://docs.rs/spl-token-metadata-interface/latest/spl_token_metadata_interface/instruction/fn.initialize.html) function.

The Token Metadata Interface ([sRFC 17](https://forum.solana.com/t/srfc-00017-token-metadata-interface/283)) is designed to work with external metadata programs, not just Token2022. These external programs might not be token programs, just metadata implementations.

In this example, I pass set an external metadata program as the `token_program_id` field which works but is confusing.

```
let accounts = TokenMetadataInitialize {
    token_program_id: ctx.accounts.metadata_program.to_account_info(), // <-- Here
    mint: ctx.accounts.mint.to_account_info(),
    metadata: ctx.accounts.metadata.to_account_info(),
    mint_authority: ctx.accounts.vending_machine_pda.to_account_info(),
    update_authority: ctx.accounts.vending_machine_pda.to_account_info(),
};
let vending_machine_pda_seeds: &[&[u8]; 2] = &[
    VENDING_MACHINE_PDA_SEED.as_bytes(),
    &[ctx.bumps.vending_machine_pda],
];
let signer_seeds = &[&vending_machine_pda_seeds[..]];
let cpi_ctx = CpiContext::new_with_signer(
    ctx.accounts.metadata_program.to_account_info(),
    accounts,
    signer_seeds,
);
token_metadata_initialize(
    cpi_ctx,
    token_metadata.name,
    token_metadata.symbol,
    token_metadata.uri,
)?;
```

**Comment by jacksondoherty** [comment]
If this moves ahead, we should do similarly for `TokenGroupInitialize` and `TokenMemberInitialize`

**Comment by acheroncrypto** [comment]
I'm usually against making breaking name changes, but we can make an exception for this case since all other fields looks to be the exact same as the [`spl_token_metadata_interface::instruction::initialize`](https://docs.rs/spl-token-metadata-interface/0.4.0/spl_token_metadata_interface/instruction/fn.initialize.html) function's parameters, so it makes sense `program_id` is also the same. It also wouldn't be difficult to adapt this change since it's the only field that changes.

Happy to take a look if you'd like to make a PR for this.

**Comment by jacksondoherty** [comment]
PR here: #3076
