### ISSUE TITLE
Meet inconvenience to get CPI logs from off chain side.

### ISSUE THREAD

**Issue by bryantalexander513** [coral-xyz/anchor#3081]
It seems that it is a little complicated to decode CPI logs while writing TS tests for CPI events call.
The transaction hash should be collected after executing transactions and fetch it, then decode it to check CPI events.
Are there any ways to debug it through program log events so that we can get it easily?

**Comment by acheroncrypto** [comment]
> It seems that it is a little complicated to decode CPI logs while writing TS tests for CPI events call.

Agreed.

> The transaction hash should be collected after executing transactions and fetch it, then decode it to check CPI events.

Events are a bit redundant if you're the one both triggering and listening to them (at the same place).

> Are there any ways to debug it through program log events so that we can get it easily?

Not currently, as how we get them is completely different. However, there is https://github.com/coral-xyz/anchor/pull/2886 which adds some convenient methods to handle CPI events client side.

This issue is essentially the same as https://github.com/coral-xyz/anchor/issues/2609, let's track it there.
