### ISSUE TITLE
better error message if toolchain specified in `Anchor.toml` isn't installed

### ISSUE THREAD

**Issue by jim4067** [coral-xyz/anchor#3147]
When running solana 1.18.8 and I specify 1.18.20 in the toolchain section of my `Anchor.toml`, it errors out with this cryptic message

```bash
thread 'main' panicked at cli/src/lib.rs:545:18:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
``` 

It would be better if an error message like `specifid toochain unavailable locally` and give the user the option to install it

**Comment by acheroncrypto** [comment]
This should already work if you specify the version correctly (without spaces or unsupported characters). Can you show the `[toolchain]` section of your `Anchor.toml`?

**Comment by jim4067** [comment]
> Can you show the [toolchain] section of your `Anchor.toml`
 
```toml
[toolchain]
anchor_version = "0.30.1"  
solana_version = "1.18.20"  
```

steps to reproduce. 

1. switch to 1.18.8
2. try running `anchor build`

**Comment by acheroncrypto** [comment]
The issue is `solana-install >1.18.19` logs:

```
⚠️  solana-install is deprecated and will be discontinued when v1.18 is no longer supported. Please switch to Agave: https://github.com/anza-xyz/agave/wiki/Agave-Transition
```

https://github.com/solana-labs/solana/commit/526b7faeb5d4523ad2430298a703951ad585e549

which makes parsing the version fail.

We'll migrate to the new one for the next version, but you can use any version before `1.18.19` ([`1.18.17` is recommended](https://www.anchor-lang.com/release-notes/0.30.1#recommended-solana-version)).
