### ISSUE TITLE
avm can install a version no more than 0.27.0

### ISSUE THREAD

**Issue by shpindler** [coral-xyz/anchor#3190]
avm can install a version no more than 0.27.0, though avm list shows that the latest version is 0.30.1.

**Comment by acheroncrypto** [comment]
Please share the problem you're running into in detail when creating issues, otherwise we'll waste time going back-and-forth asking unnecessary questions.

`avm` can install all versions, but you might run into problems if you have `rustc 1.80`. In that case, see https://github.com/coral-xyz/anchor/pull/3143's description. If not, you can reopen this issue and explain the problem in detail.
