### ISSUE TITLE
Anchor fails to create expected IDL name

### ISSUE THREAD

**Issue by Sabnock01** [coral-xyz/anchor#3353]
If you have a program with a name like `program_v1`, the resulting IDL will be named `program_v1.json` yet the Mocha tests will expect `program_v_1.json`.

Tests should use the same name resolution as Anchor in generating the IDL.

Reproduced:
![image](https://github.com/user-attachments/assets/e0f623c0-1d10-494d-8731-4f7cecc93fa4)

**Comment by acheroncrypto** [comment]
Reason explained here:

https://github.com/coral-xyz/anchor/blob/8dca0d6b2bee5f6e1e3afc797804c485e592f876/ts/packages/anchor/src/workspace.ts#L27-L42

I guess we could add an edge case to check both versions, but generally speaking, you'd have much better time if you avoid using numbers in your identifiers (program name, function name, account name...) because case conversion cross-language can be inconsistent or lossy.
