### ISSUE TITLE
Can anchor test loads other smart contracts?

### ISSUE THREAD

**Issue by J0HnNy-W** [coral-xyz/anchor#3390]
Is there a way to load other smart contracts on my local machine when I run the anchor test command?

For some reasons (such as wanting to load metaplex when testing). During development, I use:
```bash
"solana-test-validator -r --bpf-program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s ./metaplex-local-validator/mpl-token-metadata.so
```

I hope to load these smart contracts when running tests. I have read the documentation and cli implementation, but I did not find this function. Am I missing something? Or is there another way to achieve it?
Thank you

**Comment by acheroncrypto** [comment]
Yes, there are multiple ways to achieve this:

- Using `test.genesis` (see https://www.anchor-lang.com/docs/manifest#test)
- Using `test.validator.clone` (see https://www.anchor-lang.com/docs/manifest#test-validator)
- Passing the arguments to the `anchor test` command (note the extra `--`):
    ```
    anchor test -- --bpf-program metaqbxxUerdq28cj1RbAWkYQm3ybzjb6a8bt518x1s ./metaplex-local-validator/mpl-token-metadata.so
    ```

Also, please use [the Solana StackExchange](https://solana.stackexchange.com) or [the Anchor Discord](https://discord.gg/NHHGSXAnXk) instead of GitHub for questions like this in the future.
