### ISSUE TITLE
warning: unexpected `cfg` condition value: `custom-heap`  --> programs/voting/src/lib.rs:7:1

### ISSUE THREAD

**Issue by sflomm** [coral-xyz/anchor#3401]
I've tried installing anchor + SOLANA as per the docs 5 times now, the local validator works and i can push npx create-solana-dapp to a local port and the connect to the local net. 
However i keep getting these warnings everytime i compile with "anchor build" using mods like #[account].

![image](https://github.com/user-attachments/assets/d2803d6f-b439-4392-b5e7-1102c78dae4a)
![image](https://github.com/user-attachments/assets/c4a8f496-d606-46ab-ba22-5a26c95fbf51)
![image](https://github.com/user-attachments/assets/c7050371-43e8-4e5c-8bb3-d4e49a944e4f)
![image](https://github.com/user-attachments/assets/7b94f56d-194e-4095-b998-992daba22086)

I always get anchor-debug, solana and custom-panic, no matter what mod i use.

**Comment by acheroncrypto** [comment]
Thanks for creating the issue. This is a recent `nightly` compiler change, but it's quite useless in this case since they are resulting from external macros. You can ignore these warnings by including:

```rs
#![allow(unexpected_cfgs)]
```

at the top of your `lib.rs` file.

We also decided to ignore all `nightly` compiler warnings recently in https://github.com/coral-xyz/anchor/pull/3396 in order to avoid showing redundant warnings.

**Comment by sky64** [comment]
Adding fresh data since this came up again while closing solvela-ai/solvela#114 against `anchor-lang 0.31.1`.

**The warnings are no longer nightly-only.** They now fire on stable rustc — current repro on rustc 1.95.0 (cargo 1.95.0) against `anchor-lang = "0.31.1"`. We empirically confirmed they also still fire on `anchor-lang = "1.0.2"` (8 of 14 warnings remain), so they aren't fixed by the macro-crate updates in the 0.32 → 1.0 line either. The four distinct values seen are `feature = "anchor-debug"`, `feature = "custom-heap"`, `feature = "custom-panic"`, and `target_os = "solana"`.

**`#![allow(unexpected_cfgs)]` works but is coarse.** It also masks any *future* unexpected-cfg drift in the same crate (e.g., a typoed feature gate elsewhere). Since [Cargo 1.79](https://blog.rust-lang.org/2024/06/13/Rust-1.79.0.html#inline-const-expressions) the `[lints.rust]` table accepts a `check-cfg` whitelist, which is the rustc team's intended escape hatch for exactly this scenario:

\`\`\`toml
[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = [
    'cfg(feature, values("anchor-debug", "custom-heap", "custom-panic"))',
    'cfg(target_os, values("solana"))',
] }
\`\`\`

Cleared all 14 warnings in our crate without suppressing the lint globally — that's what we shipped in solvela-ai/solvela#314 ahead of an `anchor-lang` bump.

**The durable fix lives in the macro crates.** Right now `anchor-attribute-program` and `anchor-derive-accounts` emit `cfg(feature = "custom-heap")` / `cfg(feature = "custom-panic")` / `cfg(feature = "anchor-debug")` / `cfg(target_os = "solana")` checks inside generated code, but they don't declare those cfgs as known-valid in the consuming crate. Two upstream-side options:

1. Have the macros emit `#[allow(unexpected_cfgs)]` on the generated code — surgical, doesn't suppress lints in user-authored code.
2. Have `anchor-lang` (or a build script in it) emit a `cargo::rustc-check-cfg=cfg(...)` directive — declares the cfgs cleanly so the lint stays useful elsewhere.

Either would close the case for new projects without requiring downstream copy-paste. Happy to send a PR if maintainers have a preference between the two — let me know.

(Downstream workaround from solvela-ai/solvela@1e80296 / PR #314 if anyone lands here from a search.)
