### ISSUE TITLE
Mobile (Flutter) client

### ISSUE THREAD

**Issue by GENL** [coral-xyz/anchor#864]
First of all, GREAT job with Anchor. 
Please are planning to create a mobile client to communicate with the deployed Anchor programs? 
Or, is there any resource that we can follow?

**Comment by leonardgee** [comment]
React Native?

**Comment by cbosborn** [comment]
We've been exploring `react-native` + `anchor`. We've run into the following issues, which so far we've addressed downstream in our own project. Can use this to think about changes, if any, we'd want to make to anchor:

1. `fs` is problematic, I think, because react native isn't recognized as a browser environment, so you run into issues like:
```
error: Error: Unable to resolve module fs from /path/to/node_modules/@project-serum/anchor/dist/cjs/workspace.js: fs could not be found within the project or in these directories:
  node_modules

  42 |             return undefined;
  43 |         }
> 44 |         const fs = require("fs");
     |                             ^
  45 |         const process = require("process");
  46 |         if (!_populatedWorkspace) {
  47 |             const path = require("path");
```
which may be resolved with the following: https://stackoverflow.com/a/39068031. We needed `fs` & `path`.

2. Looks more like a solana issue than anchor, but `superstruct` is raising the following issue with a missing `.cjs` file (swapping in the present `.es.js` file may address this):
```
error: Error: While trying to resolve module `superstruct` from file `/path/to/node_modules/@solana/web3.js/lib/index.browser.esm.js`, the package `/path/to/node_modules/superstruct/package.json` was successfully found. However, this package itself specifies a `main` module field that could not be resolved (`/path/to/node_modules/superstruct/lib/index.cjs`
```

**Comment by safaiyeh** [comment]
@cbosborn I didn't have luck using `rn-nodeify` but using metro bundle's `resolver.extraNodeModules` helped resolved this for me.

Basically for every node js function you need to switch it with the corresponding React Native equivalent. You want to make sure the path is to your node_modules that contain the package (I'm in a mono repo so that path may be different for you).

Then you can simply add a sourceExts array that contains js/ts + the needed CommonJS extension 
```
  resolver: {
    extraNodeModules: {
      stream: path.resolve(__dirname, '../../node_modules/stream-browserify'),
      os: path.resolve(__dirname, '../../node_modules/react-native-os'),
      path: path.resolve(__dirname, '../../node_modules/path-browserify'),
      fs: path.resolve(__dirname, '../../node_modules/react-native-level-fs'),
    },
    sourceExts: ["jsx", "js", "ts", "tsx", "cjs"],
  },
```

Some these dependencies need additional peer ones so look into the warnings you get.

**Comment by safaiyeh** [comment]
I can write a quick doc for the site on how to build on react native

**Comment by awcchungster** [comment]
@safaiyeh a Gist would be super helpful. I'm about to start integrate my Solana Token with a React Native app too.

**Comment by safaiyeh** [comment]
@awcchungster my snippet above should help.

**Comment by tapizquent** [comment]
Any news on Flutter + Anchor?

**Comment by Henry-E** [comment]
Someone would have to pick this up and take action on it, until then I'm closing.
