### ISSUE TITLE
Update SPL token init to use `initialize_account3`

### ISSUE THREAD

**Issue by Henry-E** [coral-xyz/anchor#963]
There is now a function to init SPL token accounts without requiring the rent account. Would be good to upgrade to use this when possible.
<https://github.com/solana-labs/solana-program-library/blob/287c3bedaf5ee5b49983495fd2826e84d35bc561/token/program/src/instruction.rs#L806>

**Comment by armaniferrante** [comment]
Labeling this as blocked since the new version of the spl-token crate has not yet been published on crates.io.

**Comment by paul-schaaf** [comment]
can update init mint as well with `initialize_mint2`

**Comment by archseer** [comment]
Since rent is now accessible via [`Rent::get()`](https://github.com/solana-labs/solana-program-library/commit/44ad2ff5b4ac294f05dc39c694deed56a1b9a6ea#diff-5ea2835329c180f1904bd576297797243f7203392ada64bdd08724ce2c40cf62R37) (https://github.com/solana-labs/solana/pull/16422), we could do a similar optimization on contexts that use `init`/`init_if_needed` with currently require a rent account. That would make it a bit nicer to use too, since adding `init` without a rent account will result in a compilation error right now.

**Comment by ceciEstErmat** [comment]
Can i try to do it ? Pretty new to rust but if its changing methods i might handle that :D

**Comment by dahifi** [comment]
> Can i try to do it ? Pretty new to rust but if its changing methods i might handle that :D

Go for it!

**Comment by jeduan** [comment]
Methods don't exist in the latest version on crates.io (3.2.0) as of 11/26

**Comment by paul-schaaf** [comment]
spl-token 3.3.0 is live on mainnet. This is no longer blocked!

**Comment by fanatid** [comment]
`spl-token:3.3.0` which introduced `initialize_account3` requires `solana-program:^1.9.2` so we sill blocked :)
https://crates.io/crates/spl-token/3.3.0/dependencies

**Comment by fanatid** [comment]
Blocked by https://github.com/project-serum/anchor/issues/1669
